baseurl             = "https://yoshicode.com/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa"
author              = "Yoshi Takashiba"
title               = "yoshicode"
pygmentsuseclasses  = true
# disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-51810510-15"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "English blog"
weight                 = -120
identifier             = "en"
url                    = "/en/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Code"
weight                 = -100
identifier             = "code"
url                    = "https://github.com/yoshicode"

[params]
include_rss            = false                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Yoshi Takashiba"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Yoshi Takashiba's own blog content."
email                  = "yoshihito522@gmail.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/yoshicode"
instagram              = "//instagram.com/yoshicode"
lang                   = "en"
linkedin               = "//linkedin.com/in/yoshicode"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "Discover new world with childlike curiosity."                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/yoshicode"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

gitalk                 = false
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "your client id"
gitalk_clientSecret    = "your client secret"
gitalk_repo            = "your repo url"
gitalk_owner           = "the owner of this repo"
gitalk_admin           = ['a', 'list', 'of', 'administrator']

avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.

[taxonomies]
tag = "tags"